backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: "static/uploads"
public_folder: "/uploads"
# publish_mode: editorial_workflow

# show_preview_links: true
# site_url: https://taupe-heliotrope-97d179.netlify.app
# display_url: https://taupe-heliotrope-97d179.netlify.app/
# logo_url: https://your-site.com/images/logo.svg

collections:
  - name: listings
    label: listings
    folder: src/lib/content/listings
    create: true
    extension: json
    summary: "{{title}} (/{{filename}})" #customize w/ title, date and url button
    preview_path: listings/{{slug}}
    fields:
      # Main data
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      # Basic facts
      - label: "Address"
        name: "address"
        widget: "object"
        collapsed: false
        fields:
          - {
              label: "Street Address",
              name: "street",
              widget: "string",
              required: false,
            }
          - { label: "City", name: "city", widget: "string" }
          - { label: "State", name: "state", widget: "string" }
          - {
              label: "Postal Code",
              name: "post-code",
              widget: "string",
              required: false,
            }
          - {
              label: "County",
              name: "county",
              widget: "string",
              required: false,
            }
      - label: "Acres"
        name: "acres"
        widget: "number"
        value_type: "float"
        min: 0
      - label: "Price"
        name: "price"
        widget: "number"
        value_type: "int"
        min: 0
      # Details and descriptions
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
      - label: "Slideshow Images"
        name: "slideshow_images"
        widget: "list"
        required: false
        field: { label: "Slideshow Image", name: "image", widget: "image" }
      - label: "Description"
        name: "description"
        widget: "richtext"
        required: false
      - label: "Details"
        name: "details"
        widget: "richtext"
        required: false
      - label: "Summary"
        name: "summary"
        widget: "object"
        collapsed: false
        required: false
        fields:
          - label: "Feature Categories"
            name: "feature_categories"
            widget: "list"
            required: false
            fields:
              - {
                  label: "Feature Category",
                  name: "feature_category",
                  widget: "string",
                }
              - { label: "List of Features", name: "features", widget: "list" }
          - { label: "Land Details", name: "land_details", widget: "list" }
          - label: "Distances"
            name: "distances"
            widget: "list"
            fields:
              - {
                  label: "City/Interstate/Attraction",
                  name: "location",
                  widget: "string",
                }
              - {
                  label: "Distance (miles)",
                  name: "distance",
                  widget: "number",
                  value_type: "float",
                  min: 0,
                }
          - label: "Utilities"
            name: "utilities"
            widget: "list"
            required: false
            fields:
              - { label: "Utility", name: "utility", widget: "string" }
              - label: "Availability"
                name: "availability"
                widget: "select"
                multiple: false
                options:
                  - { label: "Onsite", value: "Onsite" }
                  - { label: "Nearby", value: "Nearby" }
                  - { label: "Unavailable", value: "Unavailable" }
          - { label: "Housing", name: "housing", widget: "list" }
          - { label: "Improvements", name: "improvements", widget: "list" }
      - label: "Download Brouchure"
        name: "brouchure"
        widget: "file"
        required: false
      - label: "Location"
        name: "location"
        widget: "map"
        required: false

  - name: team
    label: team
    folder: src/lib/content/team
    create: true
    extension: json
    widget: list
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Position, name: position, widget: string }
      - { label: Photo, name: photo, widget: image }
