backend:
  name: git-gateway
  branch: master
collections:
  - name: routes
    label: routes
    folder: src/routes
    create: true
    extension: json
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"

# when using the default proxy server port
local_backend: true

# site_url: https://your-site.com
# display_url: https://your-site.com
# logo_url: https://your-site.com/images/logo.svg